import {
  BarChart3,
  Boxes,
  ChefHat,
  ClipboardList,
  CreditCard,
  DatabaseBackup,
  Flag,
  Gift,
  HeartHandshake,
  LifeBuoy,
  LockKeyhole,
  MapPinned,
  MessageCircle,
  Newspaper,
  PlugZap,
  Rocket,
  Settings,
  Shield,
  ShieldCheck,
  Star,
  Store,
  Tags,
  Truck,
  Users,
} from "lucide-react";

export const adminLinks = [
  { href: "/admin", label: "Overview", icon: Shield, group: "Control" },
  { href: "/admin/users", label: "Users", icon: Users, group: "People" },
  { href: "/admin/stores", label: "Stores", icon: Store, group: "People" },
  { href: "/admin/riders", label: "Riders", icon: Truck, group: "People" },
  { href: "/admin/products", label: "Products", icon: Boxes, group: "Marketplace" },
  { href: "/admin/restaurants", label: "Restaurants", icon: ChefHat, group: "Marketplace" },
  { href: "/admin/food", label: "Food menu & categories", icon: ChefHat, group: "Marketplace" },
  { href: "/admin/orders", label: "Orders", icon: ClipboardList, group: "Operations" },
  { href: "/admin/deliveries", label: "Deliveries", icon: MapPinned, group: "Operations" },
  { href: "/admin/chats", label: "Chats", icon: MessageCircle, group: "Operations" },
  { href: "/admin/reviews", label: "Reviews", icon: Star, group: "Moderation" },
  { href: "/admin/reports", label: "Reports", icon: Flag, group: "Moderation" },
  { href: "/admin/boosts", label: "Adverts", icon: Rocket, group: "Growth" },
  { href: "/admin/coupons", label: "Coupons", icon: Gift, group: "Growth" },
  { href: "/admin/billing", label: "Billing", icon: CreditCard, group: "Growth" },
  { href: "/admin/analytics", label: "Analytics", icon: BarChart3, group: "Insights" },
  { href: "/admin/notifications", label: "Notifications", icon: HeartHandshake, group: "Insights" },
  { href: "/admin/cms", label: "CMS", icon: Newspaper, group: "Content" },
  { href: "/admin/categories", label: "Categories", icon: Tags, group: "Content" },
  { href: "/admin/towns", label: "Towns", icon: MapPinned, group: "Content" },
  { href: "/admin/locations", label: "Locations", icon: MapPinned, group: "Content" },
  { href: "/admin/verification", label: "Verification", icon: ShieldCheck, group: "Security" },
  { href: "/admin/integrations", label: "API connections", icon: PlugZap, group: "Security" },
  { href: "/admin/settings", label: "Platform settings", icon: Settings, group: "System" },
  { href: "/admin/roles", label: "Roles", icon: LockKeyhole, group: "System" },
  { href: "/admin/audit-log", label: "Audit log", icon: ClipboardList, group: "System" },
  { href: "/admin/support", label: "Support", icon: LifeBuoy, group: "System" },
  { href: "/admin/backup", label: "Backup", icon: DatabaseBackup, group: "System" },
  { href: "/admin/rewards", label: "Rewards", icon: Gift, group: "System" },
];
