import {
  BarChart3,
  Boxes,
  ChefHat,
  ClipboardList,
  CreditCard,
  DatabaseBackup,
  Flag,
  Gift,
  HeartHandshake,
  LifeBuoy,
  LockKeyhole,
  MapPinned,
  MessageCircle,
  Newspaper,
  PlugZap,
  Rocket,
  Settings,
  Shield,
  ShieldCheck,
  Star,
  Store,
  Tags,
  Truck,
  Users,
} from "lucide-react";

export const adminLinks = [
  { href: "/admin", label: "Overview", icon: Shield },
  { href: "/admin/users", label: "Users", icon: Users },
  { href: "/admin/stores", label: "Stores", icon: Store },
  { href: "/admin/riders", label: "Riders", icon: Truck },
  { href: "/admin/products", label: "Products", icon: Boxes },
  { href: "/admin/restaurants", label: "Restaurants", icon: ChefHat },
  { href: "/admin/food", label: "Food menu & categories", icon: ChefHat },
  { href: "/admin/orders", label: "Orders", icon: ClipboardList },
  { href: "/admin/deliveries", label: "Deliveries", icon: MapPinned },
  { href: "/admin/chats", label: "Chats", icon: MessageCircle },
  { href: "/admin/reviews", label: "Reviews", icon: Star },
  { href: "/admin/reports", label: "Reports", icon: Flag },
  { href: "/admin/boosts", label: "Adverts", icon: Rocket },
  { href: "/admin/coupons", label: "Coupons", icon: Gift },
  { href: "/admin/billing", label: "Billing", icon: CreditCard },
  { href: "/admin/analytics", label: "Analytics", icon: BarChart3 },
  { href: "/admin/notifications", label: "Notifications", icon: HeartHandshake },
  { href: "/admin/cms", label: "CMS", icon: Newspaper },
  { href: "/admin/categories", label: "Categories", icon: Tags },
  { href: "/admin/towns", label: "Towns", icon: MapPinned },
  { href: "/admin/locations", label: "Locations", icon: MapPinned },
  { href: "/admin/verification", label: "Verification", icon: ShieldCheck },
  { href: "/admin/integrations", label: "API connections", icon: PlugZap },
  { href: "/admin/settings", label: "Platform settings", icon: Settings },
  { href: "/admin/roles", label: "Roles", icon: LockKeyhole },
  { href: "/admin/audit-log", label: "Audit log", icon: ClipboardList },
  { href: "/admin/support", label: "Support", icon: LifeBuoy },
  { href: "/admin/backup", label: "Backup", icon: DatabaseBackup },
  { href: "/admin/rewards", label: "Rewards", icon: Gift },
];
