import {
  Bell,
  ChefHat,
  GitCompareArrows,
  Heart,
  LifeBuoy,
  MapPinned,
  MessageCircle,
  PackageCheck,
  Search,
  ShoppingBag,
  ShoppingCart,
  Star,
  Trophy,
  UserRound,
  Users,
  Wallet,
} from "lucide-react";

export const buyerLinks = [
  { href: "/buyer", label: "Overview", icon: ShoppingBag },
  { href: "/marketplace", label: "Browse products", icon: Search },
  { href: "/food", label: "Food near me", icon: ChefHat },
  { href: "/cart", label: "Cart", icon: ShoppingCart },
  { href: "/buyer/orders", label: "Orders", icon: PackageCheck },
  { href: "/buyer/food-orders", label: "Food orders", icon: ChefHat },
  { href: "/buyer/address-book", label: "Address book", icon: MapPinned },
  { href: "/buyer/following", label: "Following", icon: Users },
  { href: "/favorites", label: "Favorites", icon: Heart },
  { href: "/buyer/wishlist", label: "Wishlist", icon: Heart },
  { href: "/buyer/reviews", label: "Reviews", icon: Star },
  { href: "/buyer/saved-searches", label: "Saved searches", icon: Bell },
  { href: "/buyer/compare", label: "Compare", icon: GitCompareArrows },
  { href: "/buyer/wallet", label: "Wallet", icon: Wallet },
  { href: "/buyer/loyalty", label: "Loyalty", icon: Trophy },
  { href: "/buyer/support", label: "Support", icon: LifeBuoy },
  { href: "/chat", label: "Chats", icon: MessageCircle },
  { href: "/profile", label: "Profile", icon: UserRound },
];
