import {
  BarChart3,
  Bell,
  BriefcaseBusiness,
  ClipboardList,
  CreditCard,
  FileText,
  HeartHandshake,
  Megaphone,
  MessageCircle,
  PackagePlus,
  Settings,
  ShieldCheck,
  Store,
  Truck,
  UserCog,
  Users,
  Warehouse,
} from "lucide-react";

export const sellerLinks = [
  { href: "/seller", label: "Overview", icon: Store },
  { href: "/seller/store", label: "Store management", icon: Settings },
  { href: "/seller/products/new", label: "Add product", icon: PackagePlus },
  { href: "/seller/services/new", label: "Add service", icon: BriefcaseBusiness },
  { href: "/seller/inventory", label: "Inventory", icon: Warehouse },
  { href: "/seller/orders", label: "Orders", icon: ClipboardList },
  { href: "/seller/delivery", label: "Delivery", icon: Truck },
  { href: "/seller/analytics", label: "Analytics", icon: BarChart3 },
  { href: "/seller/adverts", label: "Promotions", icon: Megaphone },
  { href: "/seller/reviews", label: "Reviews", icon: HeartHandshake },
  { href: "/seller/followers", label: "Followers", icon: Users },
  { href: "/seller/notifications", label: "Notifications", icon: Bell },
  { href: "/seller/reports", label: "Reports", icon: FileText },
  { href: "/seller/staff", label: "Staff", icon: UserCog },
  { href: "/seller/payouts", label: "Payouts", icon: CreditCard },
  { href: "/seller/store", label: "Verification", icon: ShieldCheck },
  { href: "/chat", label: "Buyer messages", icon: MessageCircle },
];
