import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";
import { LEGAL_CONTACT_EMAIL } from "@/lib/legal";

const sections: LegalSection[] = [
  { id: "license", title: "Limited platform license", paragraphs: ["Subject to your compliance with this Agreement and the Terms of Use, the ShopLinkk operator grants you a limited, personal, revocable, non-exclusive, non-transferable license to access and use the ShopLinkk web application for lawful local marketplace activity."] },
  { id: "ownership", title: "Platform ownership", paragraphs: ["The platform software, interface, ShopLinkk name and visual identity, original text, data arrangement, and operator-created assets are owned by or licensed to the ShopLinkk operator. No ownership is transferred to you. User-submitted listings remain subject to the content provisions in the Terms."] },
  { id: "permitted", title: "Permitted use", bullets: ["Browse, search, save, compare, and contact sellers for personal or legitimate business marketplace activity.", "Create and manage accurate stores and listings when your account permits it.", "Use admin tools only within an authorized staff role and documented responsibility.", "Download or display content only through features ShopLinkk expressly provides."] },
  { id: "restrictions", title: "Restrictions", bullets: ["Do not copy, resell, sublicense, rent, mirror, or commercially exploit the application itself.", "Do not reverse engineer, bypass access controls, probe security, inject code, overload APIs, or automate scraping without written authorization.", "Do not remove copyright, license, attribution, security, or brand notices.", "Do not use the platform or its data to train, populate, or operate a competing marketplace without written permission.", "Do not use admin credentials, integrations, or personal data outside the purpose for which access was granted."] },
  { id: "updates", title: "Updates and feature changes", paragraphs: ["The operator may deploy fixes, security changes, interface updates, integrations, and new features. Some updates may be required to continue using the service. A future mobile application or payment feature may include additional license terms."] },
  { id: "open-source", title: "Open-source and third-party components", paragraphs: ["ShopLinkk uses open-source libraries and adapted MIT-licensed UI elements. Those components remain governed by their own notices and licenses. The source repository includes a THIRD_PARTY_NOTICES file for attributed UI patterns. This Agreement does not reduce rights granted by an applicable open-source license."] },
  { id: "feedback", title: "Feedback", paragraphs: ["If you voluntarily submit product feedback or suggestions, you allow the operator to use them without restriction or payment, provided the operator does not claim ownership of unrelated confidential information or your existing intellectual property."] },
  { id: "security", title: "Security and account controls", paragraphs: ["The license is tied to your authorized account and role. You must not share staff access, API credentials, private integration keys, or session tokens. The operator may revoke sessions, rotate secrets, restrict devices, or suspend access to protect the platform."] },
  { id: "termination", title: "Termination", paragraphs: ["This license ends automatically when your account is deleted, your access is terminated, or you materially breach this Agreement. On termination, stop accessing restricted platform functions. Provisions concerning ownership, restrictions, liability, and open-source notices survive where their nature requires it."] },
  { id: "disclaimer", title: "No warranty and liability", paragraphs: ["The application is provided on an as-available basis to the extent permitted by Ghanaian law. The liability provisions in the Terms of Use apply to this license. Open-source components are provided under the warranty disclaimers in their respective licenses."] },
  { id: "law", title: "Law, complete agreement, and contact", paragraphs: [`This Agreement is governed by Ghanaian law and forms part of the ShopLinkk Terms of Use. If a provision is unenforceable, the remaining provisions continue. Questions may be sent to ${LEGAL_CONTACT_EMAIL}.`] },
];

export default function LicenseAgreementPage() {
  return <LegalDocument eyebrow="License" title="ShopLinkk Platform License Agreement" introduction="This Agreement explains the limited right to use the ShopLinkk application and protects the platform, its users, and licensed third-party components." sections={sections} />;
}
