import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";
import { LEGAL_CONTACT_EMAIL } from "@/lib/legal";

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance of these Terms", paragraphs: ["By creating an account, signing in, browsing listings, sending messages, requesting an advert, or otherwise using ShopLinkk, you agree to these Terms, the Privacy Policy, the Acceptable Use Policy, the Platform License Agreement, and the Community Rules. If you do not agree, do not use the service."] },
  { id: "eligibility", title: "Eligibility and accounts", paragraphs: ["You must be legally able to enter a binding agreement under Ghanaian law. A parent or lawful guardian must supervise any permitted use by a minor."], bullets: ["Provide accurate, current account information and keep it updated.", "Protect your password, verification codes, and signed-in devices.", "Do not sell, share, impersonate, or create deceptive accounts.", "Tell ShopLinkk promptly if you suspect unauthorized access."] },
  { id: "platform-role", title: "ShopLinkk's role", paragraphs: ["ShopLinkk is a local marketplace and communications platform. It helps buyers discover listings and contact independent sellers. ShopLinkk is not the seller, buyer, delivery company, insurer, escrow agent, or payment processor for a transaction unless a future service is expressly introduced under separate terms.", "Online payment is not currently available. Buyers and sellers arrange inspection, pickup, delivery, negotiation, and any lawful payment independently."] },
  { id: "seller-duties", title: "Seller and listing duties", bullets: ["Only list products or services you lawfully own, control, or are authorized to offer.", "Use accurate titles, descriptions, prices, condition labels, locations, photos, and videos.", "Disclose material defects, restrictions, delivery terms, and whether the price is negotiable.", "Keep availability and stock status current and mark completed listings sold.", "Do not manipulate ratings, duplicate listings, keywords, locations, or account identity."] },
  { id: "buyer-duties", title: "Buyer responsibilities", paragraphs: ["A buyer must assess whether a listing and seller are suitable before agreeing to a deal. Product approval is a moderation decision, not a warranty of authenticity, quality, ownership, safety, legality, or fitness."], bullets: ["Ask questions and inspect the actual item before paying.", "Meet in a public, safe place and take another person when appropriate.", "Verify phones, electronics, vehicle or land documents, receipts, serial numbers, and ownership where relevant.", "Do not send deposits or advance payments to unknown persons solely because a listing appears on ShopLinkk."] },
  { id: "communication", title: "Chat and direct contact", paragraphs: ["Messages must relate to lawful marketplace activity. ShopLinkk may deliver messages in real time and may send email, SMS, or in-app notifications. Contact details may be shown when a user chooses seller contact options.", "ShopLinkk administrators do not routinely read private conversations. A reported message or conversation may be reviewed to investigate abuse, protect users, preserve evidence, or comply with law."] },
  { id: "prohibited", title: "Prohibited products and conduct", bullets: ["Illegal, stolen, counterfeit, recalled, unsafe, or fraudulently described goods.", "Weapons, unlawful drugs, exploitative content, trafficking, financial scams, or services that facilitate crime.", "Harassment, threats, hate, sexual exploitation, spam, phishing, malware, or attempts to obtain passwords and verification codes.", "False identity, fake documents, fake reviews, price baiting, duplicate or misleading listings, and unauthorized scraping.", "Circumventing blocks, moderation, rate limits, account restrictions, or platform security."] },
  { id: "moderation", title: "Approval, reports, and moderation", paragraphs: ["Listings may remain private while awaiting approval. ShopLinkk may approve, reject, request changes, expire, unfeature, remove, or preserve a listing. Accounts may be warned, limited, suspended, or banned with a reason where practical.", "Users may report products, sellers, accounts, and chat messages. Reports must be honest and must not be used to harass competitors. Moderation records and audit logs may be retained for safety and legal purposes."] },
  { id: "adverts", title: "Seller adverts and promotion fees", paragraphs: ["A seller may request a sponsored homepage or marketplace placement. The admin may set an offline fee, duration, start date, placement, and campaign conditions. A request is not live until approved and marked paid or waived by an authorized admin.", "Promotion affects visibility only. It does not guarantee impressions, messages, sales, ranking outside the agreed placement, or seller verification. Unless the admin confirms otherwise in writing, time already delivered is not refundable. ShopLinkk may pause an advert if the listing becomes sold, removed, unsafe, inaccurate, or unlawful."] },
  { id: "content-license", title: "Your content and permission to display it", paragraphs: ["You retain ownership of lawful text, photos, video, logos, and other content you submit. You grant the ShopLinkk operator a worldwide, non-exclusive, royalty-free license to host, store, reproduce, resize, compress, moderate, display, distribute, and promote that content only as needed to operate, secure, improve, and market the marketplace.", "You confirm that your content does not violate another person's intellectual property, privacy, publicity, or contractual rights. You may remove ordinary listings, subject to retention needed for reports, disputes, backups, and law."] },
  { id: "third-parties", title: "Third-party services", paragraphs: ["ShopLinkk may use service providers such as Google, Resend, Arkesel, Cloudinary, Pusher, Google Maps, hosting providers, and analytics or monitoring services. Their services may have separate terms, availability, security, and privacy practices. External calls, WhatsApp links, map results, and seller websites are outside ShopLinkk's control."] },
  { id: "privacy", title: "Privacy and verification", paragraphs: ["Personal data is handled under the ShopLinkk Privacy Policy. Email and phone verification improve trust but do not prove a person's character, authority, product ownership, or the safety of a transaction. A verification badge may be withdrawn if information changes or concerns arise."] },
  { id: "availability", title: "Availability and disclaimers", paragraphs: ["ShopLinkk is provided on an as-available basis. To the fullest extent permitted by law, the operator does not promise uninterrupted access, error-free data, permanent storage, exact map distance, a successful transaction, or that every user and listing is genuine. Nothing in these Terms excludes a right or remedy that Ghanaian law does not allow to be excluded."] },
  { id: "liability", title: "Limitation of liability", paragraphs: ["To the fullest extent permitted by law, the ShopLinkk operator is not liable for indirect, incidental, special, punitive, or consequential losses arising from independent buyer-seller dealings, unsafe meetings, external payments, delivery, third-party services, lost data, or unauthorized account use. Any direct liability that cannot lawfully be excluded is limited to the amount the claimant paid directly to ShopLinkk for the specific service giving rise to the claim during the preceding six months."] },
  { id: "termination", title: "Suspension, deletion, and termination", paragraphs: ["You may request account deletion through account settings. ShopLinkk may retain limited records required for security, reports, fraud prevention, legal claims, backups, or compliance. The operator may suspend or terminate access for risk, legal obligation, repeated violations, non-payment of an advert fee, or harm to the community."] },
  { id: "changes", title: "Changes to the service or Terms", paragraphs: ["ShopLinkk may change features and these Terms as the marketplace expands to new towns or introduces new services. Material changes will be communicated through the app, email, or another reasonable method. Continued use after the effective date means acceptance of the revised terms where permitted by law."] },
  { id: "law", title: "Governing law and disputes", paragraphs: ["These Terms are governed by the laws of the Republic of Ghana. The parties should first try to resolve a concern through ShopLinkk support. If it cannot be resolved, a court of competent jurisdiction in Ghana may hear the dispute, subject to any mandatory consumer or data-protection process."] },
  { id: "contact", title: "Contact", paragraphs: [`Questions about these Terms may be sent to ${LEGAL_CONTACT_EMAIL}. Legal notices should identify the account, listing, issue, and a reliable reply address.`] },
];

export default function TermsPage() {
  return <LegalDocument eyebrow="Legal" title="ShopLinkk Terms of Use" introduction="These Terms govern ShopLinkk accounts, local buying and selling, seller adverts, chat, moderation, and safe use of the platform in Ghana." sections={sections} sources={[{ label: "Electronic Transactions Act, 2008 (Act 772)", href: "https://ghalii.org/akn/gh/act/2008/772/eng%402020-12-29" }, { label: "Ghana Cyber Security Authority resources", href: "https://csa.gov.gh/resources.php" }]} />;
}
