import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";
import { LEGAL_CONTACT_EMAIL } from "@/lib/legal";

const sections: LegalSection[] = [
  { id: "scope", title: "Scope", paragraphs: ["This Privacy Policy explains how the ShopLinkk operator collects, uses, stores, discloses, and protects personal data when people use the website, marketplace, account tools, chat, seller services, adverts, and support channels."] },
  { id: "data", title: "Data we collect", bullets: ["Account data: name, email, phone, password hash, profile photo, role, location, and verification status.", "Seller data: store details, address area, opening hours, WhatsApp number, verification documents, ratings, response activity, and trust indicators.", "Marketplace data: listings, prices, descriptions, images, videos, drafts, favorites, comparisons, saved searches, price alerts, views, and advert requests.", "Communication and safety data: chat messages, attachments, reports, blocks, moderation notes, suspension reasons, audit records, and support requests.", "Technical data: session identifiers, browser and device details, timestamps, IP-derived security signals, logs, errors, and rate-limit events.", "Location data: a selected town or area and, only with device permission, temporary browser geolocation used to sort nearby towns."] },
  { id: "sources", title: "How data is collected", paragraphs: ["Data comes from you, your use of ShopLinkk, linked sign-in or communications providers, sellers and buyers who interact with you, administrators who moderate the service, and technical providers that operate the platform. We do not ask providers for more account data than is reasonably needed for the selected feature."] },
  { id: "purposes", title: "Why we use data", bullets: ["Create, authenticate, recover, secure, and manage accounts.", "Publish approved listings and stores, enable search, maps, favorites, comparisons, alerts, adverts, and direct contact.", "Deliver chat, email, SMS OTP, verification, report, and notification services.", "Detect spam, suspicious keywords, duplicate or unsafe listings, abuse, and unauthorized access.", "Moderate users and content, investigate reports, keep audit records, and enforce platform rules.", "Measure product and seller performance and improve reliability, accessibility, search, and mobile experience.", "Meet lawful requests, preserve legal claims, and comply with Ghanaian law."] },
  { id: "grounds", title: "Legal grounds and consent", paragraphs: ["Depending on the activity, processing may be necessary to perform the platform agreement, protect legitimate marketplace and security interests, comply with a legal duty, or act on consent. Optional device location, marketing, and certain notifications may be withdrawn through device or account settings. Withdrawal does not affect earlier lawful processing."] },
  { id: "public", title: "Information visible to others", paragraphs: ["Approved listings and stores may show seller name, store name, profile image, town or area, seller contact methods, verification status, ratings, listing media, and response indicators. Do not publish a home address, identity number, password, OTP, financial credentials, or another person's private data in a listing or chat."] },
  { id: "providers", title: "Service providers and international processing", paragraphs: ["ShopLinkk may send limited data to hosting and database providers and to configured providers such as Google for sign-in and maps, Resend for email, Arkesel for SMS OTP, Cloudinary for media, Pusher for realtime events, and monitoring or backup services. Some providers process data outside Ghana. We select providers for a defined purpose and use available contractual, security, and account controls."] },
  { id: "sharing", title: "When data may be disclosed", bullets: ["To another user when required for a listing, store, chat, report, or transaction contact flow.", "To service providers acting for ShopLinkk under appropriate instructions.", "To a regulator, court, law-enforcement body, or adviser when legally required or reasonably necessary to protect rights and safety.", "During a lawful restructuring or transfer of the platform, with appropriate confidentiality and notice where required.", "With your direction or consent."] },
  { id: "retention", title: "Retention", paragraphs: ["Account and marketplace data is kept while the account or listing is active and for a reasonable period afterward. Verification tokens expire quickly. Security logs, reports, audit records, backups, and transaction-related communications may be retained longer where needed to prevent fraud, resolve disputes, comply with law, or establish legal claims. Data is deleted or anonymized when it is no longer reasonably required."] },
  { id: "security", title: "Security", paragraphs: ["ShopLinkk uses password hashing, protected sessions, role checks, rate limits, encrypted integration secrets, restricted uploads, moderation controls, and provider security features. No internet service can guarantee absolute security. Users must protect passwords and OTP codes and report suspected compromise promptly."] },
  { id: "rights", title: "Your choices and data rights", bullets: ["Review and update profile and store information.", "Control favorites, alerts, saved searches, contact methods, and device location permission.", "Request access, correction, deletion, restriction, or an explanation of personal-data use, subject to lawful exceptions.", "Object to or withdraw consent for eligible processing.", "Complain to ShopLinkk and, where applicable, the Ghana Data Protection Commission."] },
  { id: "children", title: "Children", paragraphs: ["ShopLinkk is not designed for unsupervised use by children. We do not knowingly seek personal data from a child who cannot lawfully consent or contract. A parent or guardian may contact us about an account or data concern."] },
  { id: "automation", title: "Safety signals and automated assistance", paragraphs: ["ShopLinkk may use rules to flag suspicious terms, repeated content, unusual request volume, expired listings, or possible duplicates. These signals assist moderation and do not by themselves make a final legal judgment. Administrators can review and act on flagged content."] },
  { id: "changes", title: "Policy changes", paragraphs: ["We may update this Policy as ShopLinkk adds towns, providers, or features. Material changes will be shown in the service or communicated through a reasonable channel, with a new effective date."] },
  { id: "contact", title: "Contact and complaints", paragraphs: [`Send privacy requests to ${LEGAL_CONTACT_EMAIL}. Include enough information to locate the account and verify that the request concerns you. Do not email passwords, OTP codes, or identity documents unless an authorized support process specifically requests them.`] },
];

export default function PrivacyPage() {
  return <LegalDocument eyebrow="Privacy" title="ShopLinkk Privacy Policy" introduction="This Policy describes the personal data needed to operate a trusted Ghana marketplace and the choices available to buyers, sellers, and staff." sections={sections} sources={[{ label: "Data Protection Commission documents", href: "https://dataprotection.org.gh/documents/" }, { label: "Data Protection Commission privacy guidance", href: "https://dataprotection.org.gh/privacy-policy/" }]} />;
}
